export const GET_SECURITY_FORM_DATA = `
query {
    getSecurityList {
     z_id
    security_id 
    first_name
    last_name
    permanent_address
    current_address
    state
    pincode
    country
    city
    whatsapp_num
    bank_account_num
    bank_name
    account_holder_name
    bank_branch_name
    ifsc_code
    bank_passbook_img
    joining_date
    joining_salary
    current_salary
    previous_work_description
    adhar_num 
    pan_num
    gender
    contact_num 
    email
    date_of_birth
    age
    qualification
    profile_img
    adhar_img
    pan_img
    cdate
    ctime
    udate
    utime
    }
  }
`;