export const GET_NURSERY_ADMISSION_DATA = `
query {
    getNurseryAdmissionList {
      z_id
      student_id
      first_name
      middle_name
      class_title
      last_name
      gender
      date_of_birth
      blood_group
      adhar_no
      category
      mother_tangue
      father_full_name
      mother_full_name
      father_work
      mother_work
      guardian_whatsapp_number
      guardian_mobile_number
      guardian_email_id
      guardian_religion
      guardian_annual_income
      permanent_address
      permanent_address_nearest_policestation
      permanent_address_nearest_landmark
      permanent_address_state
      permanent_address_district
      permanent_address_tehsil
      permanent_address_post_office
      permanent_address_pincode
      permanent_address_type
      nationality
      current_address
      current_address_nearest_policestation
      current_address_nearest_landmark
      current_address_state
      current_address_district
      current_address_tehsil
      current_address_post_office
      current_address_pincode
      current_address_type
      country
      student_profile_image
      student_aadhar_front
      student_aadhar_back
      father_aadhar_front
      father_aadhar_back
      mother_aadhar_front
      mother_aadhar_back
      student_birth_certificate
      payment_id
      payment_status
      payment_transaction_id
      payment_date
      total_fees
      paid_amount
      payment_method
      cdate
      ctime
      udate
      utime
      success_msg
      error_msg
      admission_status  
profile_verification  
student_aadhar_front_verification  
student_aadhar_back_verification  
father_aadhar_front_verification  
father_aadhar_back_verification  
mother_aadhar_front_verification  
mother_aadhar_back_verification  
birth_certificate_verification  
mobile_number_verification  
email_verification  
whatsapp_number_verification  

    }
  }
`;