export const GET_NURSERY_ADMISSION_DATA = `
query {
    getNurseryAdmissionList {
      z_id
    student_id
    first_name
    middle_name
    last_name
    adhar_num
    father_name
    mother_name
    father_contact_num
    father_email
    father_occupation
    dob
    gender
    permanent_address
    current_address
    city
    state
    pincode
    nationality
    religion
    caste
    admission_status
    admission_fee
    student_adhar_front_img
    student_adhar_back_img
    father_adhar_front_img
    father_adhar_back_img
    mother_adhar_front_img
    mother_adhar_back_img
    father_pancard_img
    student_profile_img
    student_birth_certificate_img
    payment_id
    admission_fees
    payment_method
    payment_status
    payment_transaction_id
    payment_date
    total_fees
    paid_amount
    due_amount
    cdate
    ctime
    udate
    utime
    }
  }
`;