export const GET_TRANSPORT_VEHICLE_DATA = `
query {
    getTransportVehicleRegistration {
      z_id
    vehicle_id
    vehicle_number
    vehicle_type
    fuel_type
    seating_capacity
    vehicle_img
    model
    chassis_number
    engine_number
    insurance_policy_number
    insurance_policy_certificate
    insurance_expiry_date
    fitness_certificate_expiry_date
    puc_certificate
    permit_number
    permit_expiry_date
    status
    gps_tracker_id
    owner_first_name
    owner_middle_name
    owner_last_name
    owner_address
    owner_mobile_num
    alternate_mobile_num
    owner_email
    owner_whatsapp_num
    owner_dob
    owner_pincode
    owner_district
    owner_state
    owner_country
    owner_adhar_num
    owner_pan_num
    owner_adhar_img
    owner_pan_img
    owner_bank_passbook_img
    bank_name
    bank_account_holder_name
    bank_ifsc
    bank_account_num
    bank_branch_code
    bank_branch_name
    cdate
    ctime
    udate
    utime
    }
  }
`;