export const GET_USER_MANAGEMENT_DATA = `
query {
    getUserManagementData {
           z_id
      first_name
      middle_name
      last_name
      userid
      gender
      email
      contact_no
      role
      status
      subject_specialization
      class_assigned
      teacher_id
      admin_id
      joining_date
      qualification
      enrollment_no
      date_of_birth
      standard
      section
      parent_id
      admission_date
      children_id
      occupation
      address
      nationality
      profile_img
      adhar_card_front_img
      adhar_card_back_img
      pan_card_img
      cdate
      ctime
      udate
      utime
    }
  }
`;